version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "10:93:44:3c:5a:16:8a:9a:53:32:9b:fb:79:bf:fd:39"
      - run:
          name: echo path
          command: pwd
      - run:
          name: Deploy Over SSH
          command: scp -r target/* $SSH_USER@$SSH_HOST:/root/cirleci/
      - run: echo '部署完毕'

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context: deploy
          requires:
            - build
