version: 2.1

jobs:
  build-and-publish:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - add_ssh_keys:
          fingerprints:
            - "10:93:44:3c:5a:16:8a:9a:53:32:9b:fb:79:bf:fd:39"
      - run:
          name: Publish Over SSH
          command: scp target/graphql-sample-0.0.1-SNAPSHOT.jar $SSH_USER@$SSH_HOST:/root/cirleci/
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "10:93:44:3c:5a:16:8a:9a:53:32:9b:fb:79:bf:fd:39"
      - run: echo '部署完毕'

workflows:
  build-and-deploy:
    jobs:
      - build-and-publish
          context: deploy
      - deploy:
          context: deploy
          requires:
            - build-and-publish
